# Generated by Django 4.0 on 2022-02-08 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('many2one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='many2one.person'),
        ),
    ]
