# Generated by Django 4.0.2 on 2022-02-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_order_tag_product_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
