# Generated by Django 4.0 on 2022-02-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
